### ISSUE TITLE
Dots on Question Mark, Exclamation Mark

### ISSUE THREAD

**Issue by jdw1996** [madmalik/mononoki#10]
I really love this font. I'm using it now in my terminal and text editor. Thank you so much!

I don't know if you are interested in feedback or not, but I think it would be nice in a future version to have the dots at the bottom of the question mark and exclamation mark larger, to match with the period and colon.

With or without this change, I will be using mononoki as my go-to font for the foreseeable future. Thanks again!

**Comment by madmalik** [comment]
Thanks for the issue and your kind words!

I'll try out your suggestion. I've exaggerated the commonly used interpunction like periods and commas, since the difference is quite important while programming. But those gigantic dots look unfitting in other contexts like exclamation and questions marks and dieresis and so on. 

But i see the tension between the size differences. Maybe a can find a middle ground.

**Comment by jdw1996** [comment]
I completely understand. You're the designer; this is just my two cents.
