### ISSUE TITLE
Font derivative license question

### ISSUE THREAD

**Issue by iokasimov** [madmalik/mononoki#120]
Hi @madmalik!

I'm opening this issue to clarify some question and providing a notice on derivative of your Mononoki font.
It's going to be used as a main font for a new [programming language](https://muratkasimov.art/Ya).

I didn't change the name of the font and the type of license, only added names of people who worked on it for a while.
It's not supposed to be used commercially, anybody can download it and use without any prerequisites.

Let me know if I get something wrong so I could apply changes as fast as I can.

Font files are located [here](https://github.com/iokasimov/ya-fonts/tree/main).

P.S. Thank you for this work!

**Comment by madmalik** [comment]
Hi @iokasimov!

That sounds cool, i'm happy that you are using the font in your project!

Since you created a derivative, i would suggest creating your own license with a distinct name. I don't mind if you use "mononoki" as part of the name, but since it is technically a different font, it makes sense to make the distinction clear in the name.

In that case i think it would be best to only put the people who worked on the derivative in that license. You can then specify, that it is derived from my font and link back to this repo or the [public page](http://madmalik.github.io/mononoki/).

Sound good? :)
