### ISSUE TITLE
Provide programmer's ligatures like in Fira Code

### ISSUE THREAD

**Issue by glebd** [madmalik/mononoki#29]
https://github.com/tonsky/FiraCode

**Comment by madmalik** [comment]
Hi

I'm somewhat ambivalent about Programming Ligatures. I've experimented with them in the past, and decided to ship this font without special ligatures.
Afaik the problems are:
* For example `≠` is very different from `!=`, and since some languages allow unicode symbols it could be confusing
* Languages are very different. In Haskell `[i*i | i<-[1..]]` should be rendered as `[i*i | i⟵[1..]]`, but `if x<-3` should not become `if x ⟵3`. Lua has `~=` instead of `!=` and so on.
* The font has no context awareness. Ligatures would be shown in comments, documentation, strings...

But on the other hand, programming ligatures are a fun feature. 


So, first i have to clean up some other, more fundamental issues. But after that i could try to make specialized versions for different programming languages.

**Comment by glebd** [comment]
I agree sometimes ligatures can get a bit over the top. But they work well for me (C++, C#, F#, Swift, HTML). Some of them are harmless but make source code look nicer (</, />, ..., ///, |>, <>,  etc.) Also, some fonts (Iosevka, PragmataPro) come with a non-ligature version. Anyway, you're right, it's not a critical feature but rather a nice-to-have. Thanks again for the font.

**Comment by ooopscc** [comment]
It's great if you add this feature in another branch and provide two with- and without-ligature version. For those gays who want ligatures must take there own risk of confusing issue to use it. Thanks

**Comment by glebd** [comment]
@ooopscc did you seriously just say that?

**Comment by ooopscc** [comment]
@glebd The above confusing issues also exist in FiraCode and other similar typefaces, so why two versions is not good idea? After all, integrate ligatures is not so difficult, and Fira code provide a way to do this.

**Comment by madmalik** [comment]
@ooopscc i think (hope) you wanted to write guys (what would still be an unfortunate formulation since i hope all programming folks are able to get some utility out of this project, regardless of their gender identity or expression)

**Comment by spl** [comment]
@ooopscc: In case it wasn't clear from @madmalik's comment, I think @glebd was reacting to [your use](#issuecomment-222919266) of “gays,” not to your suggestion of another branch. I'm guessing it was a typo, and you meant “guys” in a casual sense. 😄

**Comment by ooopscc** [comment]
@spl: I didn't realize that I have made such an embarrassing typo in my comment above, even when I tried to understand @madmalik's latest comment, until you @spl reply this issue. I really don't mean "gays", so sorry for my poor English.  😁

**Comment by sib-null** [comment]
I would love to have versions that have language specific ligatures as well.  I vote for Haskell :smiley:

**Comment by demigor** [comment]
I vote for C-like & JS ligatures: ==, !=, ===, !===, => etc.

**Comment by HZooly** [comment]
Hey guys, any news about this ? 😃

**Comment by batisteo** [comment]
I thought ligatures are a font optional features that could be controlled by text editors.

**Comment by godspeedfw** [comment]
What's the status on this? Are ligatures being added/ever gonna be added?

**Comment by asemic-horizon** [comment]
I love programming ligatures in general -- with one exception: the equality comparison sign ==.

**Comment by zhaogaolong** [comment]
I use mononoki patch nerdfonts and ligatures.
https://github.com/zhaogaolong/dotfiles/tree/main/font

**Comment by madmalik** [comment]
I've tested this for a while and it just creates too many problems on some platforms and text rendering engines. I've decided not to include ligatures.

**Comment by ooopscc** [comment]
I use ligaturizer to add ligatures to mononoki, the patched font works fine for me.
