### ISSUE TITLE
En dash looks like an underscore and isn’t wide enough

### ISSUE THREAD

**Issue by kleinfreund** [madmalik/mononoki#35]
The en dash (`–`) is placed very low compared to a regular dash (`-`). It basically looks like an underscore when written in text/comments.

Also, the en dash is not as wide as the other characters. The example below as seen with the font in Sublime Text set to mononoki:

![mono](https://cloud.githubusercontent.com/assets/5774638/15452966/a2fb4c7a-2001-11e6-988f-d108899c25a5.PNG)

Example from the screenshot:

```
The en-dash – visually looks like an underscore _

A line of en-dashes separated by underscores (72 characters total):

–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_–_

A line of dashes separated by underscores (72 characters total):

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
```

This is example illustrates how the `–` almost sits at the same line as the underscore while also making the line visually shorter. The en dash `–` should sit right where the regular dash `-` is. To make the difference between the two obvious, the latter is usually made a bit shorter.

**Comment by madmalik** [comment]
The problem is: mononoki has no glyphs for em and en dash, so what you see is a replacement character from the editor. Thank you for bringing it up!

I've added both glyphs to the font and with the next release there will be correct em and en dashes. (Right now i'm collecting all issues, try to fix them and will release them all together)
