### ISSUE TITLE
Mathematical Left/Right Angle Brackets (0x27E8 and 0x27E9)

### ISSUE THREAD

**Issue by rtgill82** [madmalik/mononoki#48]
I stumbled across these in a couple of man pages if you care to add them. Other than that I haven't seen any unexpectedly missing characters in a long while.

**Comment by Goatflakes** [comment]
I also have this in Agda version 2.6.0.1 under GNU Emacs 26.1 (build 1, x86_64-w64-mingw32)
 of 2018-05-31. Don't know what release of Mononoki, though it's the latest version at time of comment. Its hash is 07f7e9bb546d8b16b6c45ea1d98b01f4a47872b3 and it was committed on the 20 April 2017.

Honestly I found this a little weird because _Programming Foundations in Agda_ https://plfa.github.io/GettingStarted/ suggests this font and uses these all the time for the _≡⟨⟩_ operator, but doesn't mention it as a problem.

This is what it appears like when you use them:
![image](https://user-images.githubusercontent.com/3669916/67861671-c6b46500-fb74-11e9-8930-594815d7c26f.png)

**Comment by madmalik** [comment]
I've added them a while ago. :)
