### ISSUE TITLE
Omitted box drawing character

### ISSUE THREAD

**Issue by kvloxx** [madmalik/mononoki#50]
This font doesn't appear to have a glyph for Unicode character U+2500, "Box Drawing Light Horizontal" in any of its styles. That code point is actually the start of the Unicode box drawing character range, so I figure there was probably an off-by-one mistake when they were generated. Hopefully an easy fix for someone who knows a little more about the process? 

Thanks for such a great face!

**Comment by jantari** [comment]
I just wanted to confirm this is still the case as of February 2019.

I noticed immediately because I use this character in my prompt, here's a screenshot:

https://i.imgur.com/Cod9MHq.png

The terminal in the back uses the Microsoft Consolas font and it depicts the character correctly.  
Mononoki in the foreground unfortunately doesn't. I know this issue has been open for a long time
now but the box drawing characters really are kind of required to be able to use this font :)

Thanks

**Comment by mikelui** [comment]
@jantari In the meantime, does the patched nerd font version work? 
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Mononoki

**Comment by madmalik** [comment]
I've added the missing character. It will be in the next release
