### ISSUE TITLE
Mononoki font appears as "Dialog" in Java on Windows

### ISSUE THREAD

**Issue by jpstotz** [madmalik/mononoki#70]
I am not sure if this a problem of the font, Windows 10 or Java (e.g. OpenJDK11, OracleJDK 8), but when I install the TrueType Fonts on Windows 10 (1909) and generate a list of all available fonts using Java the mononoki fonts end up with a font family name **Dialog** and not "Mononoki" as you would expect:

java.awt.Font[family=Dialog,name=mononoki Bold,style=plain,size=1]
java.awt.Font[family=Dialog,name=mononoki Bold Italic,style=plain,size=1]
java.awt.Font[family=Dialog,name=mononoki Italic,style=plain,size=1]
java.awt.Font[family=Dialog,name=mononoki-Regular,style=plain,size=1]

Is this a known/wanted behavior?

Java test code:

	Font fonts[] = GraphicsEnvironment.getLocalGraphicsEnvironment().getAllFonts();
	for (Font f : fonts) {
		System.out.println(f);
	}

**Comment by felis-blue** [comment]
We checked this on Mac and Linux as well as Windows and the font family name shows up correctly on Mac and Linux. On Windows, we saw a slightly different behavior than you: For mononoki-Regular the font family name was shown as "mononoki", but for the other styles it said "Dialog". @madmalik tried to look into why this is happening, but was unable to find an explanation. And since the name shows up correctly in Java on other operating systems, we are inclined to think it might be a Windows bug and not really anything that can be fixed on the side of mononoki.
