### ISSUE TITLE
Unicode Range

### ISSUE THREAD

**Issue by DecliningLotus** [madmalik/mononoki#81]
We've been supporting Mononoki at [Fontsource](https://github.com/fontsource/fontsource) for a while and I've been wondering if you could provide the values for the CSS unicode-range selector? That would be super useful for the project and users downstream.

Thanks!

**Comment by madmalik** [comment]
I've compiled the ranges and tried to find a good compromise between correctness (as in, the explicit ranges don't have many holes) and practical length, since there are quite a few characters in the upper ranges. Maybe you need to combine a few ranges that are close together if you find the expression to long:


`0020 - 04ef, 180e, 1d47, 1d9c, 1e80 - 1e85, 1ef2, 1ef3, 2000 - 2665, 27e8, 27e9, 2982, e0a0 - e0a3, e0b0 - e0b3, feff`

**Comment by DecliningLotus** [comment]
@madmalik, thank you!
