### ISSUE TITLE
Some characters have different width

### ISSUE THREAD

**Issue by Heimdell** [madmalik/mononoki#84]
This is what `alsamixer` looks like

![image](https://user-images.githubusercontent.com/1784505/130320806-f0db1ef9-ad29-486a-a3a7-e22ba9e118b3.png)

**Comment by datMaffin** [comment]
The box drawing characters in your picture look different than mononoki's. (Mononokis box drawing characters are less thick)

You could be using a mononoki version that is older than 1.2. (Box drawing seems to have been added with version 1.2)
The box drawing characters would then be substituted by some fallback font with a different width.

See also:
![image](https://user-images.githubusercontent.com/29998721/130596815-c347becd-7c82-478e-a1c2-008e7a279b42.png)
* The horizontal lines are thicker, because of #50 .
* Space between vertical lines is because of my y-offset setting

**Comment by madmalik** [comment]
Thats correct. Newer Versions should not have this problem
